spring.application.name=task-tracker-email-sender
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=email-sender-group
spring.kafka.topic.email-sending=EMAIL_SENDING_TASKS
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
