spring.application.name=task-tracker-scheduler
internal.api.key=${INTERNAL_API_KEY}
backend.url=http://localhost:8080
spring.main.web-application-type=none
spring.kafka.topic.email-sending=EMAIL_SENDING_TASKS
spring.kafka.bootstrap-servers=localhost:29092
chron.time=0 0 0 * * *

